name: Build Docker Image

on:
  push:
    branches:
      - master
    paths:
      - '!.github/**'
      - '!.env.exsample'
      - '!.gitignore'
      - '!README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to Docker Hub.
        run: |
          echo ${{ secrets.password }} | docker login -u ${{ secrets.user }} --password-stdin
      - name: Build the Docker image.
        env:
          DOCKER_BUILDKIT: 1
        run: docker build -t ${{ secrets.image_name }} .
      - name: Push to Docker Hub.
        run : docker push ${{ secrets.image_name }}
