name: Exec

on:
  # schedule:
  #   - cron: '*/5 * * * *'
  push:
    branches:
      - master

jobs:
  exec:
    runs-on: ubuntu-latest
    steps:
      - name: Notify to Slack
        env:
          SLACK_API_TOKEN: ${{ secrets.slack_token }}
          NOTIFY_CHANNEL: ${{ secrets.channel }}
        uses: 'docker://${{ secrets.image_name }}:latest'
