name: Exec

on:
  # schedule:
  #   - cron: '*/5 * * * *'
  push:
    branches:
      - master

jobs:
  exec:
    runs-on: ubuntu-latest
    steps:
      - name: Notify to Slack
        run: |
          docker run --rm \
            --env SLACK_API_TOKEN=${{ secrets.slack_token }} \
            --env NOTIFY_CHANNEL=${{ secrets.channel }} \
            ${{ secrets.image_name }}:latest
