name: Notify to Slack

on:
  schedule:
    # At 21:00 (UTC) -> 06:00 (JST)
    - cron: '00 00 21 * *'

jobs:
  exec:
    runs-on: ubuntu-latest
    steps:
      - name: Notify to Slack
        run: |
          docker run --rm \
            --env SLACK_API_TOKEN=${{ secrets.slack_token }} \
            --env NOTIFY_CHANNEL=${{ secrets.channel }} \
            ${{ secrets.image_name }}:latest
